site_name: Salon Booking Guru
site_url: https://example.com/
repo_url: https://github.com/KarmaComputing/salon-booking-guru
edit_uri: edit/main/docs
site_description: Online salon client booking and management system

nav:
    - 'Home': 'index.md'
    - 'Quick-Start Guide': 'QUICK_START_GUIDE.md'
    - 'Code of Conduct': 'CODE_OF_CONDUCT.md'
    - 'Contributing': 'CONTRIBUTING.md'
    - 'Database': 'DATABASE.md'
    - 'Wireframes': 'WIREFRAMES.md'
theme:
  name: material
