---
# When a push is made to a branch, deploy an instance of the app using
# that branch. 
# The deployed url will be <branchname>.<domain>

name: Deploy pr preview
on: 
  - pull_request
jobs:
  deploy-pr:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    environment: testing
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
      - name: Set subdomain (ensure is lowercase for dokku)
        run: |
          set -x
          echo SUBDOMAIN=`echo "${{ github.event.pull_request.user.login }}" | tr '[:upper:]' '[:lower:]' | cut -c -60` >> $GITHUB_ENV
          echo $GITHUB_ENV
        with:
          fetch-depth: 0
      - name: Deploy branch ${{ github.head_ref }} to dokku
      uses: dokku/github-action@v1.0.1
      with:
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_remote_url: ssh://${{ secrets.DOKKU_HOST }}:22/${{ env.SUBDOMAIN }}-${{ github.head_ref }}
          git_push_flags: '--force'
      - name: Click to see your PR web address
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          echo Visit your pr here: http://${{ github.event.pull_request.user.login }}-${{ github.head_ref }}.dokku.karmacomputing.co.uk
      - name: 'Comment PR with web address of application live preview'
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🙌 Live preview is here: http://${{ github.event.pull_request.user.login }}-${{ github.head_ref }}.dokku.karmacomputing.co.uk"
            })
